### PR TITLE
Expose 1more callback to decide open or not

### PR DESCRIPTION
**Pull request by binhnd-socicom**
It will be useful to support single row swipe out in ListView

### CODE REVIEW

**Comment by silentcloud** [comment]
What is the scene that  you  need `shouldOpen` ?

**Comment by binhnd-socicom** [comment]
The list view that use swipeout. Right after user try to swipe a row, the listview will know that and decide to close any opening cells.

**Comment by silentcloud** [comment]
Using `close` property would be better. @binhnd-socicom

**Comment by binhnd-socicom** [comment]
Yes, we have to use `close` to close swipeout, but when? `shouldOpen` is the trigger do that.

**Comment by binhnd-socicom** [comment]
Oh sorry. I made mistake in the PR. `shouldOpen` should be called in `_handlePanResponderGrant`

**Comment by silentcloud** [comment]
```js
this.state = {
    sectionID: null,
    rowID: null,
}
renderRow(rowData, sectionID, rowID) {
    return (
        <Swipeout
           right={[...]}
           close={!(this.state.sectionID === sectionID && this.state.rowID === rowID)}
           onOpen={(sectionID, rowID) => {
                this.setState({
                    sectionID,
                    rowID 
                })
           }}
        />
    )
}
```

@binhnd-socicom

**Comment by binhnd-socicom** [comment]
The way would close opening rows, but UX won't like iOS native.
In your code above, opening rows are only closed when other row opened. But in iOS native, the opening row is closed right after you tap or swipe any row.

**Pull request closed without merging**
