### PR TITLE
Swipe menu manual open

### PR DESCRIPTION
**Pull request by alburdette619**
This PR includes functions following the close prop architecture to open the right and left menus programmatically.  In order for this to work the PanResponder handling had to be worked on such that inside views could still have touch events.  The wrong pan methods were being used for the sensitivity to work.  Also, onClose and onOpen were only called on a pan so they were moved such that they are called in `_close()` and `_openRight/Left`.

### CODE REVIEW

**Comment by silentcloud** [comment]
@alburdette619 Thanks for your PR. Please resolve conflicts

**Comment by alburdette619** [comment]
Sorry it took me so long to get back to you on this.  It should be good to merge in if you're happy with the way I merged it all.

**Comment by cjcheshire** [comment]
This sounds very interesting as I would like to do this on my screen to suggest to users there are swipe controls.  @silentcloud are you happy with this.

Is there an example of how this works once merged?

**Comment by cjcheshire** [comment]
@alburdette619 any progress?

**Comment by lyndsey-ferguson** [comment]
I am also interested in getting this functionality.

**Comment by katmlee** [comment]
I'm also interested in this functionality +1 Thanks @alburdette619! @silentcloud any update?

**Comment by silentcloud** [comment]
This PR  is still a little problem, please consider `componentDidMount`

**Comment by rtman** [comment]
@alburdette619 @silentcloud I'd like to use this as well to open the right and left via onPress or long press, anyway we can get it finished?

**Comment by lyndsey-ferguson** [comment]
@silentcloud can you add the ability to open the swipeout manually if you're not happy with this approach?

**Comment by silentcloud** [comment]
@lyndsey-ferguson Ok, I will approve this PR, If someone  has problems using `openLeft/openRight`, welcome PR.

**Comment by silentcloud** [comment]
version 2.2.0

**Comment by CandyOgre** [comment]
@silentcloud maybe add some info to README?

**Pull request merged**
