### PR TITLE
changed to use React.Component instead of RNative

### PR DESCRIPTION
**Pull request by dozoisch**
For the dc-redux new branch.
- updated requires to support 0.25+
- also made sure the timeout is cleared on unmount.

closes #104 at the same time

### CODE REVIEW

**Comment by dieguitoweb** [comment]
+1

**Comment by aforty** [comment]
For the love of everything can this repo please be brought up to date?

**Comment by tomauty** [comment]
Waiting for NPM maintainer status :(

**Comment by jsdevel** [comment]
@dozoisch I'd happily add you as an npm / github maintainer of https://github.com/maintained-repos/react-native-swipeout if you're interested.  I'd love to see this PR get merged.

**Comment by dozoisch** [comment]
@jsdevel hey thanks! I'll try to get this PR merged in DC-REDUX. I'll open an issue on the new repo to discuss that pr since it's not on the master branch and we would have to decide if we want to go forward with that other branch.

**Comment by aliceyoung9** [comment]
Looks like this will also close #138.

**Pull request closed without merging**
