### PR TITLE
fix issue with panResponder not being able to move

### PR DESCRIPTION
**Pull request by dozoisch**

### CODE REVIEW

**Comment by tomauty** [comment]
Can you clarify what this accomplishes? Not 100% confident with panresponder methods.

**Comment by dozoisch** [comment]
Sorry for not being more verbose! I'm using that with ReactNative 0.29 right now it just wasn't doing anything. Swipe/Touching wasn't triggering anything. Adding that made it able to swipe again.

**Comment by tomauty** [comment]
All I needed to know. Thanks! Still waiting on npm access but I will merge.

**Comment by dozoisch** [comment]
@tomauty do you know if the dc redux branch will ever come to light? 

I'll pr my fixes as I use it, but it seems to work properly!

**Comment by tomauty** [comment]
Hey this is late but could you educate me on what `dc redux` is? I'm fairly new to the organization of this project.

**Comment by dozoisch** [comment]
@tomauty It's a new branch dancormier had started which is a full rewrite using animated instead of react-tween-state. I'm using a fork of that branch in a project currently. I'd be willing to make a pr with my more of my changes, but right now I've diverged quite a bit.

**Pull request merged**
