### PR TITLE
Upgrade example to v0.25 + fixed compatibility issue with v0.25

### PR DESCRIPTION
**Pull request by abelcha**

### CODE REVIEW

**Comment by magrinj** [comment]
Also fix in my previous PR #84 :)

**Comment by marcosinigaglia** [comment]
Any news from the repo owner?

**Comment by magrinj** [comment]
None since 31 Mars for me

**Comment by latusaki** [comment]
@marcosinigaglia this functionality will be in RN 27

**Comment by latusaki** [comment]
I have released a version with the RN 25 fixes, but wont be maintaining it as its obsolete now. 
https://www.npmjs.com/package/react-native-animated-swipeout

**Comment by marcosinigaglia** [comment]
The functionality is experimental, it's better not to use in production.

**Comment by latusaki** [comment]
Hm.. where did you get this information from @marcosinigaglia ? I see no comments about it on the release notes..

**Comment by marcosinigaglia** [comment]
https://github.com/facebook/react-native/tree/master/Libraries/Experimental/SwipeableRow
Each component in 'Experimental' can be removed in the new releases, I think is better use a stable library until the component 'exit' from experimental stage.

**Comment by latusaki** [comment]
Ah, didn't notice the file path. Thank you.

**Pull request closed without merging**
